int _1_dll_Test();
int _4_textFiles_Test();
int _9_lpwstrToNum_Test();
int _13_strToArrayOfNumbers_Test();
int _14_registryInOutStrings_Test();
int _17_registryInOutNumbers_Test();
int _20_messageBoxGromUtfFile_Test();
int _24_list_Test();
int _28_funPtr_Test();